build_cloud: Nitori
image: Windows

branches:
  only:
    - master

build:
  verbosity: detailed

configuration:
  - Debug
  - Release

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"

build_script:
  - cmake -G Ninja -S . -B build
  - cmake --build build

artifacts:
  - path: build/ci_test.exe
