# image: Windows
# build_cloud: Nitori

os:
  - Visual Studio 2019

platform:
  - x64

branches:
  only:
    - master

configuration:
  - Debug
  - Release

build_script:
  - cmake -S . -B build -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -A x64 -DRESTINIO_USE_EXTERNAL_EXPECTED_LITE=1 -DBUILD_SHARED_LIBS:BOOL=OFF
  - cmake --build build

after_build:
  - 7z a build\infapi.zip build\infapi.dll build\infapi.exe

artifacts:
  - path: build\infapi.zip
