build_cloud: Nitori
image: Windows

branches:
  only:
    - master

configuration:
  - Debug
  - Release

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"

build_script:
  - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
  - cmake --build build

artifacts:
  - path: build/ci_test.exe
